### ISSUE TITLE
I don't understand how to running my own instance 

### ISSUE THREAD

**Issue by Acquistapace** [Samrux/Pac-Man-Bot#4] opened 2019-06-30 20:00 UTC
Hello there, 
I try to run my own instance of this Bot because I want to customize its name, avatar, but also its games rules for a RolePlay server .. ! 
But I don't understand your instructions (i'm French but i do my best).
My goal is to host the BOT on a Raspberry Pie...

1. I installed the NET Core runtime there, 
2. Then I cloned the "master" branch into an empty directory "MyPacMan" at "Home".
3. Then I read "clone the linux-release branch for Linux systems".... 
4. I'm trying to do it but it's impossible in a non-empty directory.
So I do it in another empty directory, different from the one where the "main" branch is installed.
"MyPacMan-Linux" at "Home".
5. I add an application on Discord/Developer, I add a bot, I copy the Token, I past this Token in "config.json" present in the "bin" directory of the "MyPacMan"... 
6. I apply the 777 permissions to the "Pacman.dll" file in the "MyPacMan-Linux" dir, execute it and get the error as an attachment
![error-pacman](https://user-images.githubusercontent.com/11783294/60401427-9b4b4a80-9b81-11e9-9ef0-7eadb028c542.PNG)

I'm lost, and I need help to understand ! 

I really like your BOT and installing it in a personalized way on my Discord server is very important to me! 

So I hope you can help me understand better!

Where should we clone the "linux-release" branch?
How to launch and configure the BOT by the DLL? 
What's this about emotes to add?

Thank you for your feedback :3

**Comment by hollowstrawberry** [comment] 2019-06-30 21:33
Hello!

The problem is that the pre-existing `linux-release` branch only works on x64 linux systems, while the Raspberry Pi is an ARM linux system. To run it there, you would have to compile the bot yourself on a different machine [following the instructions](https://github.com/orchidalloy/Pac-Man-Bot#compiling-pac-man-bot) (make sure to put `linux-arm` as the runtime). Then, manually put the generated files in your raspberry pi instead of using `clone`.

If it's the first time you've compiled a .NET project and you're confused as to how, I'd be glad to assist you, or even compile it myself for you.

**Comment by Acquistapace** [comment] 2019-07-12 08:15
Hello, 
This is indeed the first time I have to compile a .NET project and I am not sure what I am doing....

I deployed a Debian 9 x64 with the prerequisites (.NET runtime & Core SDK + Visual Studio Code).

I launch a terminal and try the given command:
`dotnet publish PacManBot.csproj --runtime linux-arm --configuration Release --self-contained`

But it gives me a mistake: 
```
MSBUILD: error MSB1009: The project file does not exist.
Commutator: PacManBot.csproj
```
Do I have to create a Visual Code project named _PacManBot_ and invoked the command inside the directory? 

How and where to add the NuGet source?

And I really don't understand how the "linux-release" branch works without the bin folder (with the missing "config.json" file in the branch), without the resources,...

**_Edit :_** I found the "_PacManBot.csproj_" into the folder of the main branch but that's one of the things I don't find in "linux-release"... What exactly should I do with this branch?

**Comment by hollowstrawberry** [comment] 2019-07-12 17:45
Oh, there is a big difference with the branches: the main branch is the source code, ready to compile. The linux-release branch is the already compiled (published) program, just for convenience.

Try using dotnet publish on the main branch, where the  .csproj is found.

It seems it's now easier to add the Discord.Net library which the bot needs. Before using dotnet publish, try doing: `dotnet add package Discord.Net --version 2.1.1`

Let me know if it works.

**Comment by Acquistapace** [comment] 2019-08-18 16:15
Okay then I don't use the linux-release branch ! Thanks for the explanations !

I tried to add the nuGet package, but it returns a lot of errors :
```
root@own-pacman:/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own# dotnet add package Discord.Net --version 2.1.1
  Writing /tmp/tmpCIBV57.tmp
info : Adding PackageReference for package 'Discord.Net' into project '/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj'.
info : Restoring packages for /home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/discord.addons.emojitools/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/discord.addons.emojitools/index.json 467ms
info :   GET https://api.nuget.org/v3-flatcontainer/discord.net.rpc/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/discord.net.rpc/index.json 511ms
error: Unable to find package Discord.Addons.EmojiTools. No packages exist with this id in source(s): nuget.org
error: Unable to find package Discord.Net.Rpc with version (>= 2.0.0-beta-00860)
error:   - Found 5 version(s) in nuget.org [ Nearest version: 1.0.2 ]
error: Detected package downgrade: Discord.Net.Core from 2.1.1 to 2.0.1. Reference the package directly from the project to select a different version. 
error:  Pacman -> Discord.Net 2.1.1 -> Discord.Net.Core (>= 2.1.1) 
error:  Pacman -> Discord.Net.Core (>= 2.0.1)
error: Detected package downgrade: Discord.Net.Rest from 2.1.1 to 2.0.1. Reference the package directly from the project to select a different version. 
error:  Pacman -> Discord.Net 2.1.1 -> Discord.Net.Rest (>= 2.1.1) 
error:  Pacman -> Discord.Net.Rest (>= 2.0.1)
error: Detected package downgrade: Discord.Net.WebSocket from 2.1.1 to 2.0.1. Reference the package directly from the project to select a different version. 
error:  Pacman -> Discord.Net 2.1.1 -> Discord.Net.WebSocket (>= 2.1.1) 
error:  Pacman -> Discord.Net.WebSocket (>= 2.0.1)
error: Detected package downgrade: Discord.Net.Commands from 2.1.1 to 2.0.1. Reference the package directly from the project to select a different version. 
error:  Pacman -> Discord.Net 2.1.1 -> Discord.Net.Commands (>= 2.1.1) 
error:  Pacman -> Discord.Net.Commands (>= 2.0.1)
error: Detected package downgrade: Discord.Net.Webhook from 2.1.1 to 2.0.1. Reference the package directly from the project to select a different version. 
error:  Pacman -> Discord.Net 2.1.1 -> Discord.Net.Webhook (>= 2.1.1) 
error:  Pacman -> Discord.Net.Webhook (>= 2.0.1)
error: Package 'Discord.Net' is incompatible with 'all' frameworks in project '/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj'.
```
And so, if i tried to publish :
```
root@own-pacman:/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own# dotnet publish PacManBot.csproj --runtime %RUNTIME% --configuration Release --self-contained
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj : error NU1102: Unable to find package Discord.Net.Rpc with version (>= 2.0.0-beta-00860)
/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 1.0.2 ]
/home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj : error NU1101: Unable to find package Discord.Addons.EmojiTools. No packages exist with this id in source(s): nuget.org
  Restore failed in 1.98 sec for /home/yuzer/Documents/own-pacman/Pac-Man-Bot-Own/PacManBot.csproj.
```
I tried to add the package with Visual Studio (into a Windows client), with [dependencies](https://discord.foxbot.me/docs/guides/getting_started/installing.html?tabs=vs-install%2Ccore2-1) ..
But there's a lot of mistakes too :
![image](https://user-images.githubusercontent.com/11783294/63109321-36a94b00-bf89-11e9-8834-00e6d6d26b61.png)
If i change the "ItemGroup" of the .csproj file, it's okay but i don't think is the right way to do it.
(And that doesn't allow the addition of the package)
If i try to put the dotnet command into this projet i've a similar error :
![image](https://user-images.githubusercontent.com/11783294/63109293-23967b00-bf89-11e9-8262-7b8f48729690.png)
(This error is exactly similar without manual updates of the .csproj file)

**Comment by hollowstrawberry** [comment] 2019-08-18 16:18
Oof, seems like I'm a bit outdated by now. Not sure how to fix the package thing.

**Comment by Acquistapace** [comment] 2019-08-18 17:32
Ah, sorry about that ._.'
Can I still customize the code without this Package?
Or force the use of old versions?

**Comment by hollowstrawberry** [comment] 2019-08-19 21:36
I think you can try updating the packages to the latest versions and delete the non-existent packages. That might be easy with Visual Studio.

 When I last worked on the bot, I used a myget.org link, which might have the older versions or might not even exist anymore.

**Comment by hollowstrawberry** [comment] 2019-09-07 18:56
It occurred to me that you can try using this command to fix the packages. I'm not sure it'll work, but it's promising:
`dotnet restore -s https://www.myget.org/F/discord-net/api/v3/index.json`

Putting this here so at least other people can see.

**Comment by hollowstrawberry** [comment] 2020-11-27 17:35
The bot uses a different library now so I'll close this issue

**Closed as completed** 2020-11-27 17:35 UTC
